name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate with GCP
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # Step 3: Configure Docker for Artifact Registry
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev

    # Step 4: Set up GCP
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: qdex-401002
        export_default_credentials: true

    # Step 5: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t asia-southeast1-docker.pkg.dev/qdex-401002/gcr/oneart-product-cart-service:$GITHUB_SHA \
                     -t asia-southeast1-docker.pkg.dev/qdex-401002/gcr/oneart-product-cart-service:latest .

    # Step 6: Push the Docker image to Artifact Registry
    - name: Push Docker image
      run: |
        docker push asia-southeast1-docker.pkg.dev/qdex-401002/gcr/oneart-product-cart-service:$GITHUB_SHA \
                    asia-southeast1-docker.pkg.dev/qdex-401002/gcr/oneart-product-cart-service:latest

    # Step 7: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy oneart-product-cart-service \
          --image asia-southeast1-docker.pkg.dev/qdex-401002/gcr/oneart-product-cart-service:$GITHUB_SHA \
          --region asia-southeast1 \
          --platform managed \
          --allow-unauthenticated \
          --timeout=300s \
          --update-env-vars="DB_DSN=postgres://postgres:oneart-secret@35.244.41.139:5432/postgres?sslmode=disable,GCS_BUCKET_NAME=oneart-product-images,JWT_SECRET=supersecret"